# https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/exampleSite/config.yaml

baseURL: zwack.rocks
languageCode: en-us
defaultContentLanguage: en-us
title: "Personal Website"
enableRobotsTXT: true
enableEmoji: true
theme: hugo-theme-luna
timeout: 600000
timeZone: America/New_York

deployment:
  targets:
    name: "Live Blog"
    URL: "s3://zwack-blog-website?region=us-east-1"
    cloudFrontDistributionID: "EARKPVUM5DF03"

paginate: 10

permalinks:
  posts: /:year/:month/:day/:slug.html
  pages: /:slug.html

author:
  name: Nathan Zilora

frontmatter:
  lastmod:
    - :git
    - lastmod
    - :fileModTime
    - date
    - publishDate
    - :default

taxonomies:
  tag: "tags"
  category: "categories"

summaryLength: 70
canonifyURLs: false
relativeURLs: false

imaging:
  resampleFilter: CatmullRom
  quality: 95
  anchor: smart

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

$manuMain:
  - &mainMenuHome
    name: Home
    weight: 10
    identifier: home
    params:
      icon: eva eva-home
    url: /
  - &mainMenuAbout
    name: About
    weight: 20
    identifier: about
    params:
      icon: eva eva-heart
    url: /about/
  - &mainMenuLinks
    name: Links
    weight: 30
    identifier: links
    params:
      icon: eva eva-people
    url: /links/
  - &mainMenuArchives
    name: Archives
    weight: 40
    identifier: archives
    params:
      icon: eva eva-bar-chart
    url: /archives/
  - &mainMenuTags
    name: Tags
    weight: 50
    identifier: tags
    params:
      icon: eva eva-hash
    url: /tags/
  - &mainMenuCategories
    name: Categories
    weight: 60
    identifier: categories
    params:
      icon: eva eva-folder
    url: /categories/
  - &mainMenuGitHub
    name: GitHub
    weight: 80
    identifier: github
    params:
      icon: eva eva-github
    url: /github/
  - &mainMenuSearch
    name: Search
    weight: 999
    identifier: search
    params:
      icon: eva eva-search
    url: /search/

menu:
  main:
    - *mainMenuHome
    - *mainMenuAbout
    - *mainMenuLinks
    - *mainMenuArchives
    - *mainMenuGitHub
    - *mainMenuSearch

markup:
  highlight:
    style: dracula
    guessSyntax: true
    tabWidth: 4
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true

params:
  topTitle: false

  rss:
    enabled: true
    fullText: true

  sitemap: true
  themeColor: "#dd6065"
  blackAndWhite: false

  console:
    enabled: true
    leftColor: "#dd6065"
    leftText: "Hugo Theme Luna"
    rightColor: "#feb462"
    rightText: "Powered by Hugo ❤ Luna"

  headlineCounter: false

  fixedNav: false

  font: 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'

  customScript:
    enabled: false
    pjax: true # Auto-reload in pjax mode

  runTime:
    enabled: true
    creatTime: 2023/10/4
  

  since: "2023"


  outdatedInfoWarning:
    enabled: true
    day: 90

  autoDarkMode: true

  share:
    twitter: true
    facebook: true
    weibo: false
    copyLinkText: true
    qrcode: true
  
  qrcodeAPI: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="

  license:
    enabled: true
    name: "CC BY-NC-ND 4.0"
    icon: "Cc-by-nc-nd.svg" # in assets folder
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0"

  i18nlist: true

  github:
    id: "Zwork101"
    minStars: 5 # 最小 star 项目 / min stars

  imageZoom: true

  lazyload: true

  bionicReading:
    enabled: true
    autoBionic: false
    skipLinks: false
    excludeWords: []
    excludeNodeNames: []
    excludeClasses: ['github']

  googleTranslate: true

  pangu: true

  search: true

  lastmod: true

  readingTime: true

  wordCount: true

  toc:
    enabled: true
    wordCount: 400 

  HugoEncrypt:
    Password: "123456"
    Storage: "session"

  pjax: true

  pwa: true
  katex: true
  backtop: true

  featuredImageHeight: "42%" #42% | false

  defaultFeaturedImage: false

  imageProcessing:
    cover: true
    content: true
    autoResize:
      - 1080
      - 1440
    webp: true

  # opengraph:
  #   twitter: # see https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
  #     cardType: summary_large_image # summary | summary_large_image
  #     site: "@Ice_Hazymoon"
  #   image: "featured.png" # in assets folder | false

  author: Nathan Zilora
  keywords: # TODO: Set these
    - Blog
    - Review
  description: "A simple, performance-first, SEO-friendly Hugo theme"

build:
  noJSConfigInAssets: true

languages:
  en-us:
    contentDir: content/en-us
    languageName: English
    params:
      languageIcon: "images/i18n/en-us.svg" # in assets folder
    menu:
      main:
      - *mainMenuHome
      - *mainMenuAbout
      - *mainMenuLinks
      - *mainMenuArchives
      - *mainMenuGitHub
      - *mainMenuSearch

staticDir:
  - static